import { Beast } from '../models/beast.model';

export const BEASTS: Beast[] = [
  {
    name: 'Lion',
    species: 'Panthera leo',
    habitat: 'Savannah',
    diet: 'Carnivore',
    size: { length: 5, weight: 300 },
  },
  {
    name: 'Tiger',
    species: 'Panthera tigris',
    habitat: 'Forest',
    diet: 'Carnivore',
    size: { length: 6, weight: 400 },
  },
  {
    name: 'Bear',
    species: 'Ursus arctos',
    habitat: 'Forest',
    diet: 'Omnivore',
    size: { length: 7, weight: 500 },
  },
  {
    name: 'Wolf',
    species: 'Canis lupus',
    habitat: 'Forest',
    diet: 'Carnivore',
    size: { length: 4, weight: 200 },
  },
  {
    name: 'Elephant',
    species: 'Loxodonta africana',
    habitat: 'Savannah',
    diet: 'Herbivore',
    size: { length: 10, weight: 1000 },
  },
  {
    name: 'Giraffe',
    species: 'Giraffa camelopardalis',
    habitat: 'Savannah',
    diet: 'Herbivore',
    size: { length: 12, weight: 800 },
  },
  {
    name: 'Hyena',
    species: 'Crocuta crocuta',
    habitat: 'Savannah',
    diet: 'Carnivore',
    size: { length: 5, weight: 300 },
  },
  {
    name: 'Cheetah',
    species: 'Acinonyx jubatus',
    habitat: 'Savannah',
    diet: 'Carnivore',
    size: { length: 4, weight: 150 },
  },
  {
    name: 'Zebra',
    species: 'Equus quagga',
    habitat: 'Savannah',
    diet: 'Herbivore',
    size: { length: 7, weight: 400 },
  },
  {
    name: 'Kangaroo',
    species: 'Macropus giganteus',
    habitat: 'Grassland',
    diet: 'Herbivore',
    size: { length: 6, weight: 200 },
  },
  {
    name: 'Penguin',
    species: 'Aptenodytes patagonicus',
    habitat: 'Antarctica',
    diet: 'Carnivore',
    size: { length: 3, weight: 100 },
  },
  {
    name: 'Koala',
    species: 'Phascolarctos cinereus',
    habitat: 'Forest',
    diet: 'Herbivore',
    size: { length: 2, weight: 50 },
  },
  {
    name: 'Crocodile',
    species: 'Crocodylus niloticus',
    habitat: 'River',
    diet: 'Carnivore',
    size: { length: 15, weight: 1000 },
  },
  {
    name: 'Hippopotamus',
    species: 'Hippopotamus amphibius',
    habitat: 'River',
    diet: 'Herbivore',
    size: { length: 10, weight: 1500 },
  },
  {
    name: 'Rhino',
    species: 'Diceros bicornis',
    habitat: 'Savannah',
    diet: 'Herbivore',
    size: { length: 9, weight: 1200 },
  },
];
